# Codecov Configuration
# Documentation: https://docs.codecov.com/docs/codecov-yaml

coverage:
  status:
    project:
      default:
        target: auto
        threshold: 1%
        informational: true
    patch:
      default:
        target: auto
        threshold: 1%
        informational: true

comment:
  layout: "reach,diff,flags,files,footer"
  behavior: default
  require_changes: false

flags:
  backend:
    paths:
      - backend/
  frontend:
    paths:
      - frontend/

ignore:
  - "**/*_test.go"
  - "**/test_*.py"
  - "testdata/**/*"
  - "scripts/**/*"
  - "docs/**/*"
  - "web/**/*"
  - "cmd/**/*"

